### PR TITLE
Allow inventory table to overflow card

### PR DESCRIPTION
**Pull request by karelhala**
screenshot from 2019-02-14 13-29-31

RHIPLAT2-320

### CODE REVIEW

**Comment by ryelo** [comment]
What's the screen size for this screenshot?

**Comment by karelhala** [comment]
@ryelo I had to improvise because basic inventory table is not wide enough. But because we allow additional cells to be added we have to allow this scroll for instance in compliance detail they have 6 cells for each row and on screen smaller than 930px table overflows it's parent and data are not readable. However if the screen size is small it is rendered completely differently.

**Comment by ryelo** [comment]
@karelhala So this is a temporary fix? This should be brought up with the PF team too?

**Comment by karelhala** [comment]
@ryelo yeah temporary fix and issue has been already opened https://github.com/patternfly/patternfly-next/issues/1418

**Comment by ryelo** [comment]
Sweet!

**Pull request merged**
