### PR TITLE
Add changing location for donut's legend

### PR DESCRIPTION
**Pull request by rvsia**
Add option to **change location** of the **Donut's legend**

### Options:
- Top
- Right
- Bottom (default)
- Left

### Example images
right-legend
top-legend

### CODE REVIEW

**Comment by rvsia** [comment]
@martinpovolny

**Comment by rvsia** [comment]
@ryelo It's updated. I had to set values of breakpoints in `src/Utilities/_variables.scss` because patternfly variables can not be imported in that case (after discussion with @karelhala).

**Comment by ryelo** [comment]
@rvsia I put out a [PR](https://github.com/RedHatInsights/insights-frontend-components/pull/87) yesterday which should fix that. Not sure if you want to rebase on that or how you'd want to approach this.

**Comment by rvsia** [comment]
@ryelo I rebased it and it's working well! :+1:

**Pull request merged**
