### PR TITLE
Tweak the wording when there's no rule hits on a system

### PR DESCRIPTION
**Pull request by bsquizz**
I think the current wording here is a little confusing, it almost reads like an error message indicating that "we have failed to fetch the data" :) But in reality, this message will be seen for a system that has no rule hits.

### CODE REVIEW

**Comment by bsquizz** [comment]
@AllenBW thoughts?

**Comment by AllenBW** [comment]
@bsquizz https://github.com/RedHatInsights/insights-frontend-components/pull/387/

🤤

**Comment by karelhala** [comment]
Let's merge this one and update #387 accordingly

**Pull request merged**
