### PR TITLE
Update pf4 react table to newest version

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Comment by jiridostal** [comment]
I need to get back to this PR. The code change in loading state causes table to shrink when loading 
image. To me it seems that colSpan does not remove "connected" columns but displays them at the end of the table.

**Comment by karelhala** [comment]
@jiridostal looks like the the colspan was badly calculated https://github.com/RedHatInsights/insights-frontend-components/blob/master/src/SmartComponents/Inventory/applications/vulnerabilities/VulnerabilitiesCveTable.js#L87

**Comment by jiridostal** [comment]
image
Yes but still - the rest of columns remain there even if colspan is set

**Pull request merged**
