### PR TITLE
updating styling for expandable rules card

### PR DESCRIPTION
**Pull request by ryelo**
[RHIADVISOR-407](https://projects.engineering.redhat.com/browse/RHIADVISOR-407)

cc: @kensible

Before:

image

After:
screen shot 2019-02-05 at 10 44 21 am
screen shot 2019-02-05 at 10 44 30 am

This also fixes 
- items inside of `code` tags wouldn't wrap and extend past the edges of the page.
- Removing unnecessary Grid components when Stacks should be used
- redundant styling

### CODE REVIEW

**Comment by dkuc** [comment]
The table looks odd to me being stretched to the entire width. I guess that's how legacy does it though, so maybe its not an issue.

**Comment by ryelo** [comment]
@dkuc I can certainly make it smaller and it would take just a few seconds, so if anyone else agrees, it'll be an easy fix.

**Comment by AllenBW** [comment]
Wait wait, so we're ok with blowing away author table style? I'm 😕

**Comment by ryelo** [comment]
@AllenBW we blew it away in classic because the author table styling is essentially non existent as well as the data (mainly the headers) being illegible being so close together.

**Pull request merged**
