### PR TITLE
Remove default actions from inventory header, add edit actions to general tab

### PR DESCRIPTION
**Pull request by karelhala**
This PR updates 2 things
* Move edit actions to general tab
* Add operating system info

### Before
Screenshot from 2019-05-02 14-25-47
Screenshot from 2019-05-02 14-25-54

### After
Screenshot from 2019-05-02 14-23-20
Screenshot from 2019-05-02 14-23-14

### CODE REVIEW

**Comment by karelhala** [comment]
ping @bclark

**Comment by bclarhk** [comment]
`UUID` and `Last seen` should be left aligned with the system name
The edit icon (pencil) is missing any padding
`Last boot time` should follow the same date formatting as `Last check-in`  and `Registered`

**Comment by karelhala** [comment]
@bclarhk thanks for the updates. Here is updated screenshot 
Screenshot from 2019-05-03 15-55-59

**Pull request merged**
