### PR TITLE
Run audit fix to remove critical vuln <?.x.?>

### PR DESCRIPTION
**Pull request by karelhala**
Run npm audit fix (had to run --force probably because of bable-plugin-lodash)

### CODE REVIEW

**Comment by ryelo** [comment]
Is there a reason that we're including patternfly-react (3) now?

**Comment by karelhala** [comment]
@ryelo forgot to remove it, but I am working on moving [PF3@pagination](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-View%20Type%3A=list&knob-Page=1&knob-Number%20of%20Pages=5&knob-Page%20Size%20Drop%20Up=true&knob-Item%20Count%3A=75&knob-Items%20Start%3A=1&knob-Items%20End=15&selectedKind=patternfly-react%2FWidgets%2FPagination&selectedStory=Pagination%20row&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) so we have easier access to it and put our styles over it. I guess I should remove it and add it in PR related to the pagination part.

**Comment by ryelo** [comment]
I don't think we want to ship pf3 stuff just because the filesize is huge. I think that should be available to the end user on their app, but we should just ship a port.

**Comment by karelhala** [comment]
@ryelo no worries, that's what externals are for. We'll ship just bridge for let's say pagination component and if someone wants to use such component he'll import it and since pf3 is in deps it will autoload it. I'll remove pf3 from this PR, it doesn't do anything with audit fix and we can continue this discussion in later PR where it actually makes sence.

**Comment by ryelo** [comment]
Sounds good! Push up a new version and I'll approve.

**Pull request merged**
