### PR TITLE
Update dropdown to be used from react-core <?.x.?>

### PR DESCRIPTION
**Pull request by karelhala**
* Update all packages to newer version
* Use dropdown from react-core

### CODE REVIEW

**Comment by ryelo** [comment]
@karelhala can you fix the broken Travis and I'll review?

**Comment by karelhala** [comment]
Oh darn it, I forgot to add dependency on font awesome sass. Fixed that

**Comment by ryelo** [comment]
@karelhala looks like some variables are missing now

**Comment by karelhala** [comment]
@ryelo these problems are caused by some changes in pf-react where they removed these dependencies. I reinstalled them and added them into `package.json` so we are sure that they are installed in consumes app as well.

**Pull request merged**
